# Generated by Django 4.2 on 2023-06-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="body",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
