# Generated by Django 4.2 on 2023-04-27 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100)),
                ("image", models.FileField(null=True, upload_to="")),
                ("mobile", models.CharField(max_length=15, null=True)),
                ("gender", models.CharField(max_length=10, null=True)),
                ("type", models.CharField(max_length=15, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=15, null=True)),
                ("image", models.FileField(null=True, upload_to="")),
                ("slug", models.SlugField(max_length=100)),
                ("gender", models.CharField(max_length=15, null=True)),
                ("company", models.CharField(max_length=100, null=True)),
                ("type", models.CharField(max_length=15, null=True)),
                ("status", models.CharField(max_length=20, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("salary", models.FloatField(max_length=20)),
                ("image", models.FileField(upload_to="")),
                ("description", models.CharField(max_length=500)),
                ("experience", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=20)),
                ("skills", models.CharField(max_length=200)),
                ("creationdate", models.DateField()),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.recruiter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume", models.FileField(null=True, upload_to="")),
                ("slug", models.SlugField(max_length=100)),
                ("apply_date", models.DateField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.job"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.studentuser",
                    ),
                ),
            ],
        ),
    ]
