# Generated by Django 4.2 on 2023-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruiter",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentuser",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
