# Generated by Django 4.2 on 2023-04-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_recruiter_is_blocked_studentuser_is_blocked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recruiter",
            name="status",
        ),
        migrations.AddField(
            model_name="recruiter",
            name="is_status",
            field=models.BooleanField(default=False),
        ),
    ]
