# Generated by Django 4.2 on 2023-04-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_remove_recruiter_status_recruiter_is_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiter",
            name="is_status",
            field=models.BooleanField(default=True),
        ),
    ]
