# Generated by Django 4.2 on 2023-04-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0004_alter_recruiter_is_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiter",
            name="is_status",
            field=models.BooleanField(default=False),
        ),
    ]
