# Generated by Django 4.2 on 2023-05-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0005_alter_recruiter_is_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruiter",
            name="status",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
