# Generated by Django 4.2 on 2023-05-02 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0006_recruiter_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recruiter",
            name="is_status",
        ),
    ]
