# Generated by Django 4.2 on 2023-05-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0007_remove_recruiter_is_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
