# Generated by Django 4.2 on 2023-05-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0009_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifyPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_code", models.CharField(max_length=255)),
            ],
        ),
    ]
