# Generated by Django 4.2 on 2023-05-17 03:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0010_verifypayment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="verifypayment",
            old_name="reference_code",
            new_name="pidx",
        ),
    ]
