# Generated by Django 4.2 on 2023-05-17 03:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0011_rename_reference_code_verifypayment_pidx"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="reference_code",
            new_name="pidx",
        ),
    ]
