# Generated by Django 4.2 on 2023-06-08 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0012_rename_reference_code_payment_pidx"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VerifyPayment",
        ),
    ]
