# Generated by Django 4.2 on 2023-06-12 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0013_delete_verifypayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
