# Generated by Django 4.2 on 2023-05-04 07:19

from django.db import migrations, models
import miscellaneous.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommonImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "image",
                    models.ImageField(upload_to=miscellaneous.models.upload_handler),
                ),
                ("directory", models.CharField(default="common", max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="InfoPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("content", models.JSONField(default=dict)),
                ("is_published", models.BooleanField(default=True)),
            ],
        ),
    ]
