# Generated by Django 4.2 on 2023-05-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miscellaneous", "0002_alter_infopage_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infopage",
            name="title",
            field=models.CharField(
                choices=[
                    ("Ab", "About Us"),
                    ("Pr", "Privacy  and Policy"),
                    ("Te", "Terms & Conditions"),
                    ("Co", "Contact"),
                    ("Na", "Navigation Bar"),
                    ("Nl", "Navigation Logo"),
                    ("Lc", "Location"),
                    ("So", "Social account"),
                    ("Fa", "FAQ / Help"),
                    ("Fo", "Footer content"),
                    ("Fg", "Footer logo"),
                    ("Br", "Browse Job Logo"),
                    ("No", "Notice"),
                    ("E1", "Extra 1"),
                    ("E2", "Extra 2"),
                    ("E3", "Extra 3"),
                ],
                max_length=3,
                unique=True,
            ),
        ),
    ]
